### PR TITLE
Add node dependencies

### PR DESCRIPTION
**Pull request by gasinvein**
`package-lock.json` doesn't seem to be needed at build time (when installing npm packages globally), just left it here for convenience.

### CODE REVIEW

**Comment by oliv3** [comment]
Thanks, please do not remove `--enable-flatpak`, it's unrelated to the issue.

**Comment by gasinvein** [comment]
Ah, okay, I assumed the option is used to avoid node dependencies.

**Comment by oliv3** [comment]
It's used to reduce the package size (e.g. removing unused test files in the flatpak).

**Comment by gasinvein** [comment]
Hmm, if you want to reduce package size further - add a top-level `cleanup` property to remove development files and static libraries (some of them are pretty big). E.g.
```yaml
cleanup:
  - "*.a"
  - "*.la"
  - /include
  - /lib/pkgconfig
```

**Comment by oliv3** [comment]
Thanks for the cleanup tip !

**Comment by oliv3** [comment]
@gasinvein Indeed, it dropped from 60.9MB to 32.0MB. Yay :)

**Review by oliv3 — APPROVED** [review]
Looks good to me.

**Comment by oliv3** [comment]
@gasinvein Merged, thanks !

**Pull request merged**
